### ISSUE TITLE
Teensy 4 for Tympan E?

### ISSUE THREAD

**Issue by shapr** [Tympan/Tympan_Rev_D_Hardware#1]
I suspect it would take a long time to update the Tympan, but the Teensy 4 is out, and much more powerful:
https://hackaday.com/2019/08/07/new-teensy-4-0-blows-away-benchmarks-implements-self-recovery-returns-to-smaller-form/

**Comment by biomurph** [comment]
Yes, I saw that and I have 2 on order.

We have the Tympan C which is actually a shield  for the Teensy 3.6, so
lashing that to the Teensy 4 would be the best development path.

-- Joel

Any noise in the prior signal has been inserted by my mobile device
