### ISSUE TITLE
RevD: Silkscreen on battery jack is wrong

### ISSUE THREAD

**Issue by chipaudette** [Tympan/Tympan_Rev_D_Hardware#4]
I noticed this a long time ago, but I don't know if we ever addressed it...

On RevD, the silkscreen for the battery jack is wrong...it shows the + and - going to the wrong traces.  

When you plug in an Adafruit battery, you can totally see that the red wire goes to the trace marked with a minus and you can see that the black wire goes to the trace marked with a plus.  Oops!

@biomurph, Since we can't change the as-built RevD boards, can you at least put a note on the schematic that the silkscreen is wrong?

**Comment by biomurph** [comment]
That was such an unfortunate mistake.

- changed pcb silkscreen to correct orientation
- added note to schematics
- updated pdf of schematics
