### ISSUE TITLE
DAT/CLK Labels for PDM Digital Mic Switched

### ISSUE THREAD

**Issue by eyuan-creare** [Tympan/Tympan_Rev_D_Hardware#5]
The labels for the PDM mic (Data and Clock) are flipped on the Tympan Rev-D schematic.

Here is what the AIC datasheet shows:

From the AIC Datasheet
-	PDM Data is on SCLK/MFP3
![image](https://user-images.githubusercontent.com/42774675/105522569-6c3c8280-5cab-11eb-9ba7-02eefcdda47d.png)

 -	PDM Clock is on MISO/MFP4
![image](https://user-images.githubusercontent.com/42774675/105522586-6f377300-5cab-11eb-9d9a-279cff185aae.png)

And here is what the Tympan Rev-D schematic shows:

<img src = "https://user-images.githubusercontent.com/42774675/105522777-a574f280-5cab-11eb-9f0e-5821511ff0ed.png" width = 500/>

To correct this, the board labels for the 6-pin header (P2) need flipped as well:

<img src="https://user-images.githubusercontent.com/42774675/105523020-e967f780-5cab-11eb-8345-f4ab40ff6c19.png" width = 150/>

This was confirmed experimentally, but it would be good to double check the gerber traces to confirm this.

**Comment by biomurph** [comment]
This can be fixed easily by swapping the net names, and any attending silk markings.

**Comment by biomurph** [comment]
Pushed changes to solve this issue.

**Comment by eyuan-creare** [comment]
Thanks Joel! That was fast!

**Comment by eyuan-creare** [comment]
@biomurph Should we rev the pdf schematic and note the change on it? Or wait until a new board is printed?

**Comment by biomurph** [comment]
@eyuan-creare good thinking!
Just put a note on the schematics and updated the PDF
